### ISSUE TITLE
failed to setup container for group 11: Failed to set iommu for container: Input/output error

### ISSUE THREAD

**Issue by Burlter** [01org/gvt-linux#171]
Hello. I was trying to setup my virtual machine with gvt, but this error pops up:
```
qemu unexpectedly closed the monitor: 2020-09-24T04:35:09.453740Z qemu-system-x86_64: -device vfio-pci,id=hostdev0,sysfsdev=/sys/bus/mdev/devices/34658867-146a-4656-9fa5-890fdbc37010,display=on,bus=pcie.0,addr=0x9: vfio 34658867-146a-4656-9fa5-890fdbc37010: failed to setup container for group 11: Failed to set iommu for container: Input/output error

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 75, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 111, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 66, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1279, in startup
    self._backend.create()
  File "/usr/lib/python3.7/site-packages/libvirt.py", line 1234, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: внутренняя ошибка: qemu unexpectedly closed the monitor: 2020-09-24T04:35:09.453740Z qemu-system-x86_64: -device vfio-pci,id=hostdev0,sysfsdev=/sys/bus/mdev/devices/34658867-146a-4656-9fa5-890fdbc37010,display=on,bus=pcie.0,addr=0x9: vfio 34658867-146a-4656-9fa5-890fdbc37010: failed to setup container for group 11: Failed to set iommu for container: Input/output error
```
my libvirt config:
```
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>win10</name>
  <uuid>74fbf48e-30a3-413c-ac20-5dc70f6ec3e4</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/10"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit='KiB'>6242304</memory>
  <currentMemory unit='KiB'>5632000</currentMemory>
  <vcpu placement='static'>6</vcpu>
  <os>
    <type arch='x86_64' machine='pc-q35-5.1'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
    </hyperv>
    <vmport state='off'/>
  </features>
  <cpu mode='host-passthrough' check='partial'>
    <topology sockets='1' dies='1' cores='3' threads='2'/>
  </cpu>
  <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/home/tui/Virtual/WinVM.img'/>
      <target dev='sda' bus='sata'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='usb' index='0' model='qemu-xhci' ports='15'>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
    <controller type='sata' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'/>
    <controller type='pci' index='1' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='1' port='0x10'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='2' model='pcie-to-pci-bridge'>
      <model name='pcie-pci-bridge'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='3' port='0x11'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='4' port='0x12'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='5' port='0x13'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='6' port='0x14'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </controller>
    <interface type='network'>
      <mac address='52:54:00:24:8e:ea'/>
      <source network='default'/>
      <model type='rtl8139'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x01' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='spice'>
      <listen type='none'/>
      <image compression='off'/>
      <jpeg compression='never'/>
      <zlib compression='never'/>
      <playback compression='off'/>
      <streaming mode='off'/>
      <gl enable='yes' rendernode='/dev/dri/by-path/pci-0000:00:02.0-render'/>
    </graphics>
    <sound model='ich9'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1b' function='0x0'/>
    </sound>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
    </video>
    <hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci' display='on'>
      <source>
        <address uuid='34658867-146a-4656-9fa5-890fdbc37010'/>
      </source>
      <rom enabled='no'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
    </hostdev>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </memballoon>
  </devices>
  <qemu:commandline>
    <qemu:arg value='-set'/>
    <qemu:arg value='device.hostdev0.x-igd-opregion=on'/>
  </qemu:commandline>
</domain>
```
`lspci | grep -i vga`
```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
```
`dmesg | grep -i iommu`
```
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.4.60-gentoo root=/dev/mapper/root ro quiet intel_pstate=enable i915.enable_gvt=1 kvm.ignore_msrs=1 intel_iommu=on i915.enable_guc=0 epb=15 crypt_root=UUID=ebaf92a0-a5a0-4e8d-83d0-40c3fe47d5b1 root=/dev/mapper/root
[    0.100770] Kernel command line: BOOT_IMAGE=/vmlinuz-5.4.60-gentoo root=/dev/mapper/root ro quiet intel_pstate=enable i915.enable_gvt=1 kvm.ignore_msrs=1 intel_iommu=on i915.enable_guc=0 epb=15 crypt_root=UUID=ebaf92a0-a5a0-4e8d-83d0-40c3fe47d5b1 root=/dev/mapper/root
[    0.100833] DMAR: IOMMU enabled
[    0.212698] iommu: Default domain type: Translated 
[    0.358722] pci 0000:00:00.0: Adding to iommu group 0
[    0.364887] pci 0000:00:02.0: Adding to iommu group 1
[    0.364928] pci 0000:00:04.0: Adding to iommu group 2
[    0.365168] pci 0000:00:14.0: Adding to iommu group 3
[    0.365175] pci 0000:00:14.2: Adding to iommu group 3
[    0.365227] pci 0000:00:15.0: Adding to iommu group 4
[    0.365234] pci 0000:00:15.1: Adding to iommu group 4
[    0.365282] pci 0000:00:16.0: Adding to iommu group 5
[    0.365320] pci 0000:00:17.0: Adding to iommu group 6
[    0.365369] pci 0000:00:1c.0: Adding to iommu group 7
[    0.365415] pci 0000:00:1e.0: Adding to iommu group 8
[    0.365423] pci 0000:00:1e.2: Adding to iommu group 8
[    0.366819] pci 0000:00:1f.0: Adding to iommu group 9
[    0.366826] pci 0000:00:1f.2: Adding to iommu group 9
[    0.366845] pci 0000:00:1f.3: Adding to iommu group 9
[    0.366852] pci 0000:00:1f.4: Adding to iommu group 9
[    0.366903] pci 0000:01:00.0: Adding to iommu group 10
[ 4710.852228] vfio_mdev 34658867-146a-4656-9fa5-890fdbc37010: Adding to iommu group 11
```
`ls /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/`
```
i915-GVTg_V5_4  i915-GVTg_V5_8
```
`cat /usr/src/linux/.config | grep -iE 'i915_gvt|vfio'`
```
CONFIG_KVM_VFIO=y
CONFIG_DRM_I915_GVT=y
CONFIG_DRM_I915_GVT_KVMGT=y
CONFIG_VFIO_IOMMU_TYPE1=y
CONFIG_VFIO=y
# CONFIG_VFIO_NOIOMMU is not set
# CONFIG_VFIO_PCI is not set
CONFIG_VFIO_MDEV=y
CONFIG_VFIO_MDEV_DEVICE=y
```
gentoo-sources kernel 5.4.60, intel i5-8250U

**Comment by TerrenceXu** [comment]
Before you boot up VM, can you create vgpu successfully?

**Comment by Burlter** [comment]
> Before you boot up VM, can you create vgpu successfully?

```
lockalhost # echo 34658867-146a-4656-9fa5-890fdbc37010 > /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create
```
```
localhost # ls /sys/bus/pci/devices/0000:00:02.0/34658867-146a-4656-9fa5-890fdbc37010 
driver  intel_vgpu  iommu_group  mdev_type  power  remove  subsystem  uevent
```
vgpu created, i think. After that i use config above and it gives me exactly the same error.

**Comment by gviovtanni** [comment]
I'm having the exact same issue, but with base Qemu, and on Alpine Linux (custom built kernel, v5.9.8). Creating VGPUs seems to work properly (they appear in /dev/vfio and /sys).
After quite a bit of troubleshooting (and thinking there was some issue with my hardware configuration), I tried to use a base Arch Linux install, and it worked - which leads me to think that the necessary kernel options described in the wiki (CONFIG_DRM_I915_GVT, CONFIG_DRM_I915_GVT_KVMGT, CONFIG_VFIO_MDEV and CONFIG_VFIO_MDEV_DEVICE) aren't the only ones needed to make GVT-G work. I've been trying to pinpoint which one exactly, but to no avail yet. Is there something else (KVM/IOMMU related?) that needs to be enabled in the kernel configuration to make GVT-G work?

**Comment by Burlter** [comment]
> I tried to use a base Arch Linux install, and it worked

Thank you  for telling me this. That helped. I'll try to figure out which flags are the problem, but not soon

**Comment by Burlter** [comment]
UPD: Until intel fixes [the error](https://github.com/intel/gvt-linux/issues/153), I will not use this technology and search for kernel flags
